FROM appsvc/node:12-lts

LABEL NAME=idiom

# Setup app
COPY lib/package*.json ./
COPY lib/yarn.lock ./
RUN yarn install --production=false

# Copy contents
COPY lib/ .

# Build Client
RUN yarn client:build:staging

# Start Server
ENV PORT 8000
EXPOSE 8000
CMD ["yarn","server:start:staging"]