FROM node:22-bookworm-slim

LABEL NAME=idiom

ENV REACT_APP_SERVER http://127.0.0.1:8000

# Setup app
COPY lib/package*.json ./
RUN npm ci

# Copy contents
COPY lib/ .

# Build Client
RUN npm run client:build:staging

# Start Server
ENV PORT 8000
EXPOSE 8000
CMD ["npm", "run", "server:start:staging"]